/**
 * Temporary mock service. Replace these methods with real API calls when the
 * booking objects endpoint appears.
 */

/** @type {import('../types/bookingObject').BookingObject[]} */
const bookingObjects = [
  {
    id: 'spectrometer-l500',
    title: 'Спектрометр L500 для лабораторных измерений',
    type: 'Научное оборудование',
    category: 'Исследования и измерения',
    imageUrl: '/images/spectrometer.png',
    description:
      'Лабораторный спектрометр для измерений и исследовательских работ. Перед бронированием нужно изучить инструкцию и регламент безопасности.',
    location: 'Корпус L',
    room: 'L500',
    department: 'Инженерная школа',
    services: ['Спектральный анализ', 'Лабораторные измерения'],
    assets: ['Кюветы', 'Калибровочный набор', 'Рабочая станция'],
    documents: ['Инструкция по эксплуатации', 'Техника безопасности'],
    slots: [
      { date: '2026-07-01', start: '14:00', end: '16:00', available: true },
      { date: '2026-07-02', start: '10:00', end: '12:00', available: true },
      { date: '2026-07-03', start: '15:00', end: '17:00', available: false, status: 'requested' },
    ],
    requiresDocuments: true,
    requiresInstruction: true,
    moderationRequired: false,
    restrictedAccess: false,
    requiresCheckIn: true,
    requiresCheckOut: true,
    collectiveBooking: false,
    contactPerson: 'Анна Ли',
    moderator: 'Лаборатория оптических измерений',
    subAssetsCount: 3,
  },
  {
    id: 'conference-a301',
    title: 'Конференц-зал Атриум',
    type: 'Помещение',
    category: 'Встречи и мероприятия',
    imageUrl: '/images/spectrometer.png',
    description:
      'Зал для встреч, лекций и публичных мероприятий до 80 человек. Бронирование подтверждает ответственный за площадку.',
    location: 'Корпус A',
    room: 'A301',
    department: 'Административный департамент',
    services: ['Очные встречи', 'Лекции', 'Публичные мероприятия'],
    assets: ['Проектор', 'Микрофоны', 'Система видеосвязи'],
    documents: ['Правила использования площадки'],
    slots: [
      { date: '2026-07-01', start: '10:00', end: '12:00', available: false, status: 'booked' },
      { date: '2026-07-02', start: '10:00', end: '12:00', available: true },
      { date: '2026-07-02', start: '15:00', end: '18:00', available: true },
    ],
    requiresDocuments: false,
    requiresInstruction: false,
    moderationRequired: true,
    restrictedAccess: false,
    requiresCheckIn: false,
    requiresCheckOut: false,
    collectiveBooking: true,
    contactPerson: 'Ирина Волкова',
    moderator: 'Служба бронирования аудиторий',
    subAssetsCount: 0,
  },
  {
    id: 'media-studio-b120',
    title: 'Медиа-студия B120',
    type: 'Студия',
    category: 'Запись и трансляции',
    imageUrl: '/images/spectrometer.png',
    description:
      'Пространство для записи видео, подкастов и онлайн-трансляций. Доступно после короткого инструктажа по оборудованию.',
    location: 'Корпус B',
    room: 'B120',
    department: 'Медиацентр',
    services: ['Видеозапись', 'Подкаст', 'Онлайн-трансляция'],
    assets: ['Камеры', 'Петличные микрофоны', 'Свет'],
    documents: ['Инструкция по студийному оборудованию'],
    slots: [
      { date: '2026-07-01', start: '16:00', end: '18:00', available: true },
      { date: '2026-07-03', start: '12:00', end: '14:00', available: true },
    ],
    requiresDocuments: false,
    requiresInstruction: true,
    moderationRequired: false,
    restrictedAccess: false,
    requiresCheckIn: true,
    requiresCheckOut: true,
    collectiveBooking: true,
    contactPerson: 'Михаил Сон',
    moderator: 'Медиацентр',
    subAssetsCount: 4,
  },
  {
    id: 'lab-c212',
    title: 'Учебная лаборатория C212',
    type: 'Лаборатория',
    category: 'Учебная работа',
    imageUrl: '/images/spectrometer.png',
    description:
      'Лаборатория для практических занятий и групповых проектов. Для части оборудования требуются документы и допуск преподавателя.',
    location: 'Корпус C',
    room: 'C212',
    department: 'Школа естественных наук',
    services: ['Практические занятия', 'Групповые проекты'],
    assets: ['Микроскопы', 'Лабораторные столы', 'Расходные материалы'],
    documents: ['Регламент лаборатории', 'Техника безопасности'],
    slots: [
      { date: '2026-07-01', start: '18:00', end: '20:00', available: true },
      { date: '2026-07-04', start: '09:00', end: '11:00', available: true },
    ],
    requiresDocuments: true,
    requiresInstruction: false,
    moderationRequired: false,
    restrictedAccess: true,
    requiresCheckIn: true,
    requiresCheckOut: true,
    collectiveBooking: true,
    contactPerson: 'Ольга Ким',
    moderator: 'Кафедра биотехнологий',
    subAssetsCount: 8,
  },
  {
    id: 'auditorium-d410',
    title: 'Аудитория D410',
    type: 'Помещение',
    category: 'Занятия и семинары',
    imageUrl: '/images/spectrometer.png',
    description:
      'Классическая аудитория с проектором и рабочими местами. Подходит для семинаров и небольших лекций.',
    location: 'Корпус D',
    room: 'D410',
    department: 'Учебный офис',
    services: ['Семинар', 'Лекция', 'Презентация'],
    assets: ['Проектор', 'Доска', '30 рабочих мест'],
    documents: [],
    slots: [
      { date: '2026-07-01', start: '12:00', end: '14:00', available: true },
      { date: '2026-07-02', start: '09:00', end: '11:00', available: true },
    ],
    requiresDocuments: false,
    requiresInstruction: false,
    moderationRequired: false,
    restrictedAccess: false,
    requiresCheckIn: false,
    requiresCheckOut: false,
    collectiveBooking: true,
    contactPerson: 'Учебный офис',
    moderator: 'Диспетчер аудиторий',
    subAssetsCount: 0,
  },
  {
    id: 'workshop-k101',
    title: 'Проектная мастерская K101',
    type: 'Мастерская',
    category: 'Прототипирование',
    imageUrl: '/images/spectrometer.png',
    description:
      'Рабочее пространство для прототипирования и командных сессий. Требуется подтверждение и ознакомление с регламентом.',
    location: 'Корпус K',
    room: 'K101',
    department: 'Проектный офис',
    services: ['Прототипирование', 'Командная работа', 'Макетирование'],
    assets: ['3D-принтер', 'Инструменты', 'Рабочие столы'],
    documents: ['Регламент мастерской', 'Техника безопасности'],
    slots: [
      { date: '2026-07-02', start: '09:00', end: '11:00', available: true },
      { date: '2026-07-04', start: '15:00', end: '18:00', available: true },
    ],
    requiresDocuments: true,
    requiresInstruction: true,
    moderationRequired: true,
    restrictedAccess: false,
    requiresCheckIn: true,
    requiresCheckOut: true,
    collectiveBooking: true,
    contactPerson: 'Павел Чжан',
    moderator: 'Проектная мастерская',
    subAssetsCount: 6,
  },
  {
    id: 'meeting-l308',
    title: 'Переговорная L308',
    type: 'Помещение',
    category: 'Встречи и мероприятия',
    imageUrl: '/images/spectrometer.png',
    description:
      'Небольшая переговорная для рабочих встреч до 10 человек. Временно недоступна из-за обслуживания.',
    location: 'Корпус L',
    room: 'L308',
    department: 'Административный департамент',
    services: ['Рабочая встреча', 'Видеозвонок'],
    assets: ['Экран', 'Камера', 'Маркерная доска'],
    documents: [],
    slots: [],
    requiresDocuments: false,
    requiresInstruction: false,
    moderationRequired: false,
    restrictedAccess: false,
    requiresCheckIn: false,
    requiresCheckOut: false,
    collectiveBooking: true,
    contactPerson: 'Служба эксплуатации',
    moderator: 'Служба эксплуатации',
    subAssetsCount: 0,
  },
  {
    id: 'vr-room-f204',
    title: 'VR-комната F204',
    type: 'Оборудование',
    category: 'Демонстрации и обучение',
    imageUrl: '/images/spectrometer.png',
    description:
      'Комплект VR-оборудования для демонстраций и учебных сценариев. Перед использованием нужен инструктаж.',
    location: 'Корпус F',
    room: 'F204',
    department: 'Цифровая лаборатория',
    services: ['VR-демонстрация', 'Учебный сценарий'],
    assets: ['VR-шлемы', 'Контроллеры', 'Рабочая станция'],
    documents: ['Инструкция VR-комплекта'],
    slots: [
      { date: '2026-07-01', start: '14:00', end: '16:00', available: false, status: 'unavailable' },
      { date: '2026-07-02', start: '14:00', end: '16:00', available: true },
    ],
    requiresDocuments: false,
    requiresInstruction: true,
    moderationRequired: false,
    restrictedAccess: false,
    requiresCheckIn: true,
    requiresCheckOut: true,
    collectiveBooking: false,
    contactPerson: 'Денис Кузнецов',
    moderator: 'Цифровая лаборатория',
    subAssetsCount: 3,
  },
  {
    id: 'hall-sport-g001',
    title: 'Спортивный зал G001',
    type: 'Помещение',
    category: 'Спорт и активности',
    imageUrl: '/images/spectrometer.png',
    description:
      'Зал для тренировок, секций и студенческих мероприятий. Массовые бронирования проходят подтверждение.',
    location: 'Корпус G',
    room: 'G001',
    department: 'Спортивный клуб',
    services: ['Тренировка', 'Секция', 'Мероприятие'],
    assets: ['Разметка', 'Инвентарь', 'Раздевалки'],
    documents: ['Правила спортивного зала'],
    slots: [
      { date: '2026-07-03', start: '19:00', end: '21:00', available: true },
      { date: '2026-07-05', start: '10:00', end: '12:00', available: true },
    ],
    requiresDocuments: true,
    requiresInstruction: false,
    moderationRequired: true,
    restrictedAccess: false,
    requiresCheckIn: true,
    requiresCheckOut: false,
    collectiveBooking: true,
    contactPerson: 'Спортивный клуб',
    moderator: 'Спортивный клуб',
    subAssetsCount: 2,
  },
];

export async function fetchBookingObjects() {
  await new Promise((resolve) => {
    window.setTimeout(resolve, 250);
  });

  return bookingObjects;
}

export function getBookingObjectsFilterOptions(objects) {
  return {
    categories: [...new Set(objects.map((object) => object.category))],
    types: [...new Set(objects.map((object) => object.type))],
    locations: [...new Set(objects.map((object) => object.location))],
    services: [...new Set(objects.flatMap((object) => object.services))],
  };
}
